### ISSUE TITLE
Does not compile:  Error: is inaccessible due to its protection level

### ISSUE THREAD

**Issue by new-gen23** [hausfrau87/Boost_PCL_UnrealThirdPartyPlugin#2]
Converting from 4.15.3 to 4.18 triggers the error "is inaccessible due to its protection level"
Solution:https://answers.unrealengine.com/questions/718575/error-when-updating-to-418-generating-visual-studi.html

UE4_Boost.Target.cs:
change: public UE4_BoostTarget(TargetInfo Target) 
to:     public UE4_BoostTarget(TargetInfo Target) : base(Target)

and
UE4_BoostEditor.Target.cs:
change: public UE4_BoostEditorTarget(TargetInfo Target)
to:     public UE4_BoostEditorTarget(TargetInfo Target) : base (Target) 

and:
UE4_Boost.Build.cs:
change:  public UE4_Boost(TargetInfo Target)
to:         public UE4_Boost(ReadOnlyTargetRules Target) : base(Target)

Remove the part: "public override void SetupBinaries() {...}

**Comment by ValentinKraft** [comment]
Hey new-gen,

thanks for the hint. However, for me the plugin compiles as it is on UE4.18 without problems. Is it possible that the code sections you mention belong to your own code? Because I don't have such code in my plugin.

I changed however a code passage that might have caused some problems because it was deprecated. If you still need help, let me know
